spring:
  thymeleaf:
    cache: false
  #数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serveTimezone=Asia/Shanghai

    username: root
    password: 123
    hikari:
      #连接池名
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接存活时间,默认30min
      idle-timeout: 1800000
      #最大连接数，默认10
      maximum-pool-size: 10
      #从连接池返回的连接
      auto-commit: true
      #连接最大存活时间，默认为30min
      max-lifetime: 1800000
      #连接超时
      connection-timeout: 30000
      #测试连接是否可用
      connection-test-query: SELECT 1


mybatis-plus:
  #配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置MyBatis数据返回类型别名(默认别名是类名)
  type-aliases-package: com.example-seckill.pojo

#Mybatis SQL打印(方法接口所在的包，不是Mapper)
logging:
  level:
    com.example.seckill.mapper: debug
